--ЗАДАНИЕ N1
--без оптимизации
SELECT PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.PRICE, SALESREPS.NAME, OFFICES.REGION
FROM            PRODUCTS 
						  INNER JOIN  ORDERS ON PRODUCTS.MFR_ID = ORDERS.MFR AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT 
                          INNER JOIN CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM 
						  INNER JOIN SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM AND CUSTOMERS.CUST_REP = SALESREPS.EMPL_NUM 
						  INNER JOIN OFFICES ON SALESREPS.EMPL_NUM = OFFICES.MGR
						 AND SALESREPS.REP_OFFICE = OFFICES.OFFICE
WHERE REGION='Eastern'
GROUP BY PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.PRICE, SALESREPS.NAME, OFFICES.REGION

--оптимизировано в JOIN 
SELECT PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.PRICE, SALESREPS.NAME, OFFICES.REGION
FROM            PRODUCTS 
						  INNER JOIN  ORDERS ON PRODUCTS.MFR_ID = ORDERS.MFR AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT 
                          INNER JOIN CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM 
						  INNER JOIN SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM AND CUSTOMERS.CUST_REP = SALESREPS.EMPL_NUM 
						  INNER JOIN OFFICES ON SALESREPS.EMPL_NUM = OFFICES.MGR WHERE REGION='Eastern'
						 AND SALESREPS.REP_OFFICE = OFFICES.OFFICE
GROUP BY PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.PRICE, SALESREPS.NAME, OFFICES.REGION

--оптимизировано при помощи подзапроса
SELECT PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.PRICE, SALESREPS.NAME, OFFICES.REGION
FROM            PRODUCTS 
						  INNER JOIN  ORDERS ON PRODUCTS.MFR_ID = ORDERS.MFR AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT 
                          INNER JOIN CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM 
						  INNER JOIN SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM AND CUSTOMERS.CUST_REP = SALESREPS.EMPL_NUM 
						  INNER JOIN (SELECT * FROM OFFICES WHERE REGION='Eastern') as OFFICES ON SALESREPS.EMPL_NUM = OFFICES.MGR
						 AND SALESREPS.REP_OFFICE = OFFICES.OFFICE
GROUP BY PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.PRICE, SALESREPS.NAME, OFFICES.REGION



-----------------------------------------------------------------------------------------------------------------------------------------

--ЗАДАНИЕ N2
--без оптимизации
SELECT PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, avg(PRODUCTS.PRICE) as PRICE_AVG, SALESREPS.NAME, OFFICES.REGION
FROM            PRODUCTS 
						INNER JOIN  ORDERS ON PRODUCTS.MFR_ID = ORDERS.MFR AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT 
						INNER JOIN  CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM 
						INNER JOIN  SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM AND CUSTOMERS.CUST_REP = SALESREPS.EMPL_NUM 
						INNER JOIN  OFFICES ON SALESREPS.EMPL_NUM = OFFICES.MGR AND SALESREPS.REP_OFFICE = OFFICES.OFFICE
GROUP BY PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.PRICE, SALESREPS.NAME, OFFICES.REGION
HAVING avg(PRODUCTS.PRICE)>600



--ЗАДАНИЕ N2
--Вариант с оптимизацией
SELECT PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRICE_AVG, SALESREPS.NAME, OFFICES.REGION 
FROM
(
SELECT PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.MFR_ID, avg(PRODUCTS.PRICE) as PRICE_AVG
FROM            PRODUCTS 
GROUP BY PRODUCTS.PRODUCT_ID, PRODUCTS.DESCRIPTION, PRODUCTS.MFR_ID, PRODUCTS.PRICE
HAVING avg(PRODUCTS.PRICE)>600
) as PRODUCTS
						INNER JOIN  ORDERS ON  PRODUCTS.MFR_ID = ORDERS.MFR AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT 
						INNER JOIN  CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM 
						INNER JOIN  SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM AND CUSTOMERS.CUST_REP = SALESREPS.EMPL_NUM 
						INNER JOIN  OFFICES ON SALESREPS.EMPL_NUM = OFFICES.MGR AND SALESREPS.REP_OFFICE = OFFICES.OFFICE